### ISSUE TITLE
Error on give/mob-drop of card

### ISSUE THREAD

**Issue by isaaclepes** [sarhatabaot/TradingCards#57]
**Describe the bug**
when attempting to give a card to myself, the chat displays:

```
[Cards]You have given player card: common bat
I'm sorry, but there was an error performing this command.
```

No card is received

**To Reproduce**
/cards give card common bat

**Expected behavior**
receive the card

**Error Logs**
```
[15:03:34] [Server thread/ERROR]: [TradingCards] [ACF] Exception in command: cards give card common bat
[15:03:34] [Server thread/ERROR]: [TradingCards] [ACF] java.lang.NullPointerException: Cannot invoke "net.tinetwork.tradingcards.api.config.ColorSeries.getType()" because the return value of "net.tinetwork.tradingcards.tradingcardsplugin.config.settings.GeneralConfig.getColorSeries(String)" is null
[15:03:34] [Server thread/ERROR]: [TradingCards] [ACF]  at tradingcards-plugin-5.4.7-SNAPSHOT.jar//net.tinetwork.tradingcards.tradingcardsplugin.utils.CardUtil.formatLore(CardUtil.java:222)
[15:03:34] [Server thread/ERROR]: [TradingCards] [ACF]  at tradingcards-plugin-5.4.7-SNAPSHOT.jar//net.tinetwork.tradingcards.tradingcardsplugin.card.TradingCard.buildItem(TradingCard.java:26)
[15:03:34] [Server thread/ERROR]: [TradingCards] [ACF]  at tradingcards-plugin-5.4.7-SNAPSHOT.jar//net.tinetwork.tradingcards.api.card.Card.buildNBTItem(Card.java:165)
[15:03:34] [Server thread/ERROR]: [TradingCards] [ACF]  at tradingcards-plugin-5.4.7-SNAPSHOT.jar//net.tinetwork.tradingcards.api.card.Card.build(Card.java:185)
[15:03:34] [Server thread/ERROR]: [TradingCards] [ACF]  at tradingcards-plugin-5.4.7-SNAPSHOT.jar//net.tinetwork.tradingcards.tradingcardsplugin.commands.CardsCommand$GiveCommands.onGiveCard(CardsCommand.java:119)
[15:03:34] [Server thread/ERROR]: [TradingCards] [ACF]  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:03:34] [Server thread/ERROR]: [TradingCards] [ACF]  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[15:03:34] [Server thread/ERROR]: [TradingCards] [ACF]  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:03:34] [Server thread/ERROR]: [TradingCards] [ACF]  at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[15:03:34] [Server thread/ERROR]: [TradingCards] [ACF]  at tradingcards-plugin-5.4.7-SNAPSHOT.jar//net.tinetwork.tradingcards.acf.RegisteredCommand.invoke(RegisteredCommand.java:152)
[15:03:34] [Server thread/ERROR]: [TradingCards] [ACF]  at tradingcards-plugin-5.4.7-SNAPSHOT.jar//net.tinetwork.tradingcards.acf.BaseCommand.executeCommand(BaseCommand.java:577)
[15:03:34] [Server thread/ERROR]: [TradingCards] [ACF]  at tradingcards-plugin-5.4.7-SNAPSHOT.jar//net.tinetwork.tradingcards.acf.BaseCommand.execute(BaseCommand.java:513)
[15:03:34] [Server thread/ERROR]: [TradingCards] [ACF]  at tradingcards-plugin-5.4.7-SNAPSHOT.jar//net.tinetwork.tradingcards.acf.RootCommand.execute(RootCommand.java:99)
[15:03:34] [Server thread/ERROR]: [TradingCards] [ACF]  at tradingcards-plugin-5.4.7-SNAPSHOT.jar//net.tinetwork.tradingcards.acf.BukkitRootCommand.execute(BukkitRootCommand.java:81)
[15:03:34] [Server thread/ERROR]: [TradingCards] [ACF]  at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[15:03:34] [Server thread/ERROR]: [TradingCards] [ACF]  at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:897)
[15:03:34] [Server thread/ERROR]: [TradingCards] [ACF]  at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2271)
[15:03:34] [Server thread/ERROR]: [TradingCards] [ACF]  at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2082)
[15:03:34] [Server thread/ERROR]: [TradingCards] [ACF]  at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2063)
[15:03:34] [Server thread/ERROR]: [TradingCards] [ACF]  at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[15:03:34] [Server thread/ERROR]: [TradingCards] [ACF]  at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[15:03:34] [Server thread/ERROR]: [TradingCards] [ACF]  at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[15:03:34] [Server thread/ERROR]: [TradingCards] [ACF]  at net.minecraft.server.TickTask.run(TickTask.java:18)
[15:03:34] [Server thread/ERROR]: [TradingCards] [ACF]  at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:149)
[15:03:34] [Server thread/ERROR]: [TradingCards] [ACF]  at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.c(IAsyncTaskHandlerReentrant.java:23)
[15:03:34] [Server thread/ERROR]: [TradingCards] [ACF]  at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1413)
[15:03:34] [Server thread/ERROR]: [TradingCards] [ACF]  at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189)
[15:03:34] [Server thread/ERROR]: [TradingCards] [ACF]  at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:122)
[15:03:34] [Server thread/ERROR]: [TradingCards] [ACF]  at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1391)
[15:03:34] [Server thread/ERROR]: [TradingCards] [ACF]  at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1384)
[15:03:34] [Server thread/ERROR]: [TradingCards] [ACF]  at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:132)
[15:03:34] [Server thread/ERROR]: [TradingCards] [ACF]  at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1362)
[15:03:34] [Server thread/ERROR]: [TradingCards] [ACF]  at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1268)
[15:03:34] [Server thread/ERROR]: [TradingCards] [ACF]  at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[15:03:34] [Server thread/ERROR]: [TradingCards] [ACF]  at java.base/java.lang.Thread.run(Thread.java:833)
```

**Server & Plugin Versions:**
 - Server Version: 1.17.1 and 1.18.1
 - Minecraft: 1.18.1 or 1.17.1
 - TradingCards:  5.4.7-SNAPSHOT (on 1.18.1) and 5.4.6 (on 1.17.1)

**Comment by sarhatabaot** [comment]
Is this using the default setup? 
Could you zip your tradingcards setting folder and send it here? (or send it to me on discord in a dm, sarhatabaot#0428)

**Comment by isaaclepes** [comment]
It is using the settings that were auto-generated.  The first thing I tried was deleting the /plugins/TradingCards/ folder with all of it's contents and restarting the server so the plugin could regenerate them.

I'm pretty excited to migrate to your version, as you seem to be working in more features.  One thing I was hoping to check is if the decks are working for series.  In Xen's, if your current card series changes, then all cards in player decks will convert to the new series instead of remaining their original series.  You can see why this happens: Xen's decks.yml doesn't hold data on the series at all.

**Comment by sarhatabaot** [comment]
You can get a temporary fix via https://github.com/sarhatabaot/TradingCards/releases/tag/5.5.0-SNAPSHOT
I'll release a new version as soon as it's ready.

**Comment by isaaclepes** [comment]
Amazing, I will test it out later today.  It looks like you also fixed the issue with decks changing the series?
If so, that's great.  I just completed a major overhaul of the resource pack to include new cards and a model for the deck books.

**Comment by isaaclepes** [comment]
Tested the 5.0.0-SNAPSHOT today.  Apologies for the delay.  Cards do drop and the give command does work.  I noticed the old decks I had from Xen's weren't working, so I tried to give myself a new deck, however I was unable to use the "/deck 1" function, it returned the same "I'm sorry, but there was an error performing this command."

Similar, but different output in latest.log:
```
[11:30:40] [Server thread/ERROR]: [TradingCards] [ACF] Exception in command: deck 0
[11:30:40] [Server thread/ERROR]: [TradingCards] [ACF] java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.getType()" because "item" is null
[11:30:40] [Server thread/ERROR]: [TradingCards] [ACF]  at tradingcards-plugin-5.5.0-SNAPSHOT.jar//net.tinetwork.tradingcards.tradingcardsplugin.managers.TradingDeckManager.isDeck(TradingDeckManager.java:141)
[11:30:40] [Server thread/ERROR]: [TradingCards] [ACF]  at tradingcards-plugin-5.5.0-SNAPSHOT.jar//net.tinetwork.tradingcards.tradingcardsplugin.managers.TradingDeckManager.hasDeck(TradingDeckManager.java:160)
[11:30:40] [Server thread/ERROR]: [TradingCards] [ACF]  at tradingcards-plugin-5.5.0-SNAPSHOT.jar//net.tinetwork.tradingcards.tradingcardsplugin.commands.DeckCommand.dropDeckItem(DeckCommand.java:54)
[11:30:40] [Server thread/ERROR]: [TradingCards] [ACF]  at tradingcards-plugin-5.5.0-SNAPSHOT.jar//net.tinetwork.tradingcards.tradingcardsplugin.commands.DeckCommand.onGetDeck(DeckCommand.java:37)
[11:30:40] [Server thread/ERROR]: [TradingCards] [ACF]  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:30:40] [Server thread/ERROR]: [TradingCards] [ACF]  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[11:30:40] [Server thread/ERROR]: [TradingCards] [ACF]  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:30:40] [Server thread/ERROR]: [TradingCards] [ACF]  at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[11:30:40] [Server thread/ERROR]: [TradingCards] [ACF]  at tradingcards-plugin-5.5.0-SNAPSHOT.jar//net.tinetwork.tradingcards.acf.RegisteredCommand.invoke(RegisteredCommand.java:152)
[11:30:40] [Server thread/ERROR]: [TradingCards] [ACF]  at tradingcards-plugin-5.5.0-SNAPSHOT.jar//net.tinetwork.tradingcards.acf.BaseCommand.executeCommand(BaseCommand.java:577)
[11:30:40] [Server thread/ERROR]: [TradingCards] [ACF]  at tradingcards-plugin-5.5.0-SNAPSHOT.jar//net.tinetwork.tradingcards.acf.BaseCommand.execute(BaseCommand.java:513)
[11:30:40] [Server thread/ERROR]: [TradingCards] [ACF]  at tradingcards-plugin-5.5.0-SNAPSHOT.jar//net.tinetwork.tradingcards.acf.RootCommand.execute(RootCommand.java:99)
[11:30:40] [Server thread/ERROR]: [TradingCards] [ACF]  at tradingcards-plugin-5.5.0-SNAPSHOT.jar//net.tinetwork.tradingcards.acf.BukkitRootCommand.execute(BukkitRootCommand.java:81)
[11:30:40] [Server thread/ERROR]: [TradingCards] [ACF]  at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[11:30:40] [Server thread/ERROR]: [TradingCards] [ACF]  at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:869)
[11:30:40] [Server thread/ERROR]: [TradingCards] [ACF]  at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2262)
[11:30:40] [Server thread/ERROR]: [TradingCards] [ACF]  at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2073)
[11:30:40] [Server thread/ERROR]: [TradingCards] [ACF]  at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2054)
[11:30:40] [Server thread/ERROR]: [TradingCards] [ACF]  at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[11:30:40] [Server thread/ERROR]: [TradingCards] [ACF]  at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[11:30:40] [Server thread/ERROR]: [TradingCards] [ACF]  at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[11:30:40] [Server thread/ERROR]: [TradingCards] [ACF]  at net.minecraft.server.TickTask.run(TickTask.java:18)
[11:30:40] [Server thread/ERROR]: [TradingCards] [ACF]  at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[11:30:40] [Server thread/ERROR]: [TradingCards] [ACF]  at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[11:30:40] [Server thread/ERROR]: [TradingCards] [ACF]  at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1426)
[11:30:40] [Server thread/ERROR]: [TradingCards] [ACF]  at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192)
[11:30:40] [Server thread/ERROR]: [TradingCards] [ACF]  at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[11:30:40] [Server thread/ERROR]: [TradingCards] [ACF]  at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1404)
[11:30:40] [Server thread/ERROR]: [TradingCards] [ACF]  at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1397)
[11:30:40] [Server thread/ERROR]: [TradingCards] [ACF]  at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[11:30:40] [Server thread/ERROR]: [TradingCards] [ACF]  at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1375)
[11:30:40] [Server thread/ERROR]: [TradingCards] [ACF]  at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1286)
[11:30:40] [Server thread/ERROR]: [TradingCards] [ACF]  at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[11:30:40] [Server thread/ERROR]: [TradingCards] [ACF]  at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by isaaclepes** [comment]
To clarify, I am renaming the TradingCards folder to TradingCards.old before starting the server to test, so the items from Xen are simply the paper or book items with special names and lore that exist in my player inventory.
